# Generated by Django 5.0.6 on 2024-05-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionquota',
            name='quota',
            field=models.IntegerField(default=80),
        ),
    ]
